// inventist.jp 特許DB シードデータ（サンプル / イメージを含む）
// 本番では Cloudflare D1 にこの形のレコードを投入し、/api/search が D1 を参照します。
export const SEED = [
    {no:"特許第6789012号", field:"電池・材料", title:"全固体電池向け 硫化物系固体電解質の製造方法", desc:"量産時の歩留まりを改善する製法。粒径制御により界面抵抗を低減。", year:2021, status:"live", holder:"メーカー", ipc:"H01M", kw:"電池 固体電解質 硫化物 全固体 二次電池 材料 solid electrolyte"},
    {no:"特許第6711234号", field:"電池・材料", title:"リチウムイオン電池の高速充電用シリコン系負極材料", desc:"シリコン負極の膨張を抑える複合構造。サイクル寿命を向上。", year:2020, status:"live", holder:"メーカー", ipc:"H01M", kw:"電池 リチウム 負極 シリコン 急速充電 材料 anode"},
    {no:"特開2023-018245", field:"電池・材料", title:"ナトリウムイオン電池用 希少金属フリー正極材料", desc:"コバルト・ニッケルを用いない正極組成で資源リスクを低減。", year:2023, status:"pend", holder:"スタートアップ・個人", ipc:"H01M", kw:"電池 ナトリウム 正極 希少金属フリー 材料 sodium"},
    {no:"特許第6650441号", field:"電池・材料", title:"リチウム金属負極の デンドライト抑制セパレータ", desc:"析出を均一化する表面処理で短絡リスクを低減。", year:2019, status:"live", holder:"大学・研究機関", ipc:"H01M", kw:"電池 リチウム金属 デンドライト セパレータ 安全 材料"},
    {no:"特許第7088310号", field:"電池・材料", title:"廃材由来の高純度シリコン回収プロセス", desc:"低コストで太陽電池・電池向けシリコンを再生。", year:2022, status:"live", holder:"メーカー", ipc:"C01B", kw:"シリコン リサイクル 回収 材料 純度 silicon"},
    {no:"特開2024-006671", field:"電池・材料", title:"全固体電池の常温加圧成形プロセス", desc:"加熱工程を省き、積層セルの量産性を高める。", year:2024, status:"pend", holder:"大学・研究機関", ipc:"H01M", kw:"全固体 電池 成形 量産 プロセス 材料"},
    {no:"特許第6512098号", field:"電池・材料", title:"スーパーキャパシタ用 多孔質炭素電極", desc:"比表面積を高めた炭素で高出力・長寿命を実現。", year:2018, status:"live", holder:"メーカー", ipc:"H01G", kw:"キャパシタ 炭素 電極 蓄電 材料 capacitor"},
    {no:"特許第6803321号", field:"電池・材料", title:"電池劣化をAI推定するBMSアルゴリズム", desc:"充放電履歴から残存容量・劣化度を高精度に推定。", year:2021, status:"live", holder:"スタートアップ・個人", ipc:"G01R", kw:"電池 BMS 劣化 AI 推定 SOH ソフトウェア"},

    {no:"特許第7012345号", field:"AI・ソフトウェア", title:"エッジ向け軽量モデルの推論高速化手法", desc:"量子化と枝刈りを組み合わせ、消費電力を抑えつつ精度を維持。", year:2022, status:"live", holder:"メーカー", ipc:"G06N", kw:"AI 機械学習 推論 エッジ 量子化 モデル ソフトウェア edge"},
    {no:"特開2023-098765", field:"AI・ソフトウェア", title:"異常検知のための自己教師あり学習システム", desc:"ラベルなしデータから正常を学習し、製造ラインの異常を検出。", year:2023, status:"pend", holder:"スタートアップ・個人", ipc:"G06N", kw:"AI 異常検知 自己教師 学習 製造 ソフトウェア anomaly"},
    {no:"特許第6655980号", field:"AI・ソフトウェア", title:"少数データ向けデータ拡張による画像分類", desc:"限られた教師データでも頑健な分類精度を確保。", year:2020, status:"live", holder:"大学・研究機関", ipc:"G06T", kw:"AI 画像 分類 データ拡張 少数 ソフトウェア image"},
    {no:"特許第6987654号", field:"AI・ソフトウェア", title:"時系列需要予測のための注意機構モデル", desc:"季節性と外部要因を取り込み、在庫最適化に活用。", year:2021, status:"live", holder:"メーカー", ipc:"G06Q", kw:"AI 需要予測 時系列 注意機構 transformer ソフトウェア"},
    {no:"特開2024-011234", field:"AI・ソフトウェア", title:"生成AIの出力検証・ハルシネーション検出手法", desc:"根拠文書との整合性を評価し、誤生成を抑制。", year:2024, status:"pend", holder:"スタートアップ・個人", ipc:"G06F", kw:"AI 生成 LLM 検証 幻覚 hallucination ソフトウェア"},
    {no:"特許第6543210号", field:"AI・ソフトウェア", title:"雑音環境下の音声認識前処理", desc:"適応的な雑音抑制で認識率を改善。", year:2019, status:"live", holder:"大学・研究機関", ipc:"G10L", kw:"AI 音声認識 雑音 前処理 ソフトウェア speech"},
    {no:"特許第7034567号", field:"AI・ソフトウェア", title:"サプライチェーン最適化の強化学習", desc:"需給変動下での発注・配送計画を自動最適化。", year:2022, status:"live", holder:"メーカー", ipc:"G06Q", kw:"AI 強化学習 サプライチェーン 最適化 ソフトウェア"},
    {no:"特開2023-077001", field:"AI・ソフトウェア", title:"ベクトル検索による文書横断検索システム", desc:"埋め込み表現で意味の近い文書を高速に探索。", year:2023, status:"pend", holder:"スタートアップ・個人", ipc:"G06F", kw:"AI ベクトル検索 埋め込み 検索 semantic ソフトウェア"},

    {no:"特許第6955001号", field:"ロボティクス", title:"農業用ドローンの自動経路生成・散布制御", desc:"圃場形状に応じた経路最適化と、風況を考慮した散布量制御。", year:2021, status:"live", holder:"メーカー", ipc:"G05D", kw:"ドローン ロボット 農業 経路 自動 散布 drone"},
    {no:"特許第6890777号", field:"ロボティクス", title:"協働ロボットの力覚センサレス接触検知", desc:"モータ電流から接触力を推定し、追加センサなしで安全停止。", year:2020, status:"live", holder:"メーカー", ipc:"B25J", kw:"ロボット 協働 力覚 センサレス 接触 安全 cobot"},
    {no:"特開2023-055120", field:"ロボティクス", title:"柔軟グリッパによる不定形物ピッキング", desc:"形の異なる対象を破損なく把持する空気圧グリッパ。", year:2023, status:"pend", holder:"スタートアップ・個人", ipc:"B25J", kw:"ロボット グリッパ ピッキング 把持 物流 gripper"},
    {no:"特許第6601882号", field:"ロボティクス", title:"屋内自律移動のSLAM軽量化手法", desc:"低スペック機器でも動く自己位置推定・地図生成。", year:2019, status:"live", holder:"大学・研究機関", ipc:"G05D", kw:"ロボット SLAM 自律移動 地図 自己位置 navigation"},
    {no:"特許第7045678号", field:"ロボティクス", title:"双腕ロボットの動作計画最適化", desc:"干渉回避とサイクルタイム短縮を同時に実現。", year:2022, status:"live", holder:"メーカー", ipc:"B25J", kw:"ロボット 双腕 動作計画 最適化 motion planning"},
    {no:"特開2024-003388", field:"ロボティクス", title:"触覚センサ付き義手の把持力制御", desc:"接触圧に応じて握る力を自動調整する制御。", year:2024, status:"pend", holder:"大学・研究機関", ipc:"B25J", kw:"ロボット 義手 触覚 把持 福祉 prosthetic"},
    {no:"特許第6822145号", field:"ロボティクス", title:"倉庫AGVの群制御・渋滞回避", desc:"多数台の自動搬送車を渋滞なく協調走行させる。", year:2021, status:"live", holder:"スタートアップ・個人", ipc:"G05D", kw:"ロボット AGV 群制御 物流 倉庫 渋滞 fleet"},
    {no:"特許第6488901号", field:"ロボティクス", title:"産業用ドローンの耐風飛行制御", desc:"突風下でも安定した姿勢を保つ制御アルゴリズム。", year:2018, status:"live", holder:"メーカー", ipc:"B64C", kw:"ドローン 飛行 制御 耐風 産業 UAV"},

    {no:"特許第7033210号", field:"医療機器", title:"ウェアラブル生体信号のノイズ除去回路", desc:"心電・脈波計測のSNRを改善する適応フィルタ回路。", year:2022, status:"live", holder:"メーカー", ipc:"A61B", kw:"医療 ウェアラブル 生体 心電 ノイズ センサ wearable"},
    {no:"特開2023-066540", field:"医療機器", title:"内視鏡画像のリアルタイム病変強調表示", desc:"AIで病変候補を抽出し、術中映像に低遅延で重畳表示。", year:2023, status:"pend", holder:"スタートアップ・個人", ipc:"A61B", kw:"医療 内視鏡 画像 AI 病変 診断 endoscope"},
    {no:"特許第6677001号", field:"医療機器", title:"ミリ波による非接触バイタル計測", desc:"心拍・呼吸を触れずに計測。睡眠・見守り用途に。", year:2020, status:"live", holder:"大学・研究機関", ipc:"A61B", kw:"医療 非接触 バイタル ミリ波 見守り vital"},
    {no:"特許第6901230号", field:"医療機器", title:"携帯型インスリンポンプの精密投与制御", desc:"微量を安定供給する送液制御で血糖管理を支援。", year:2021, status:"live", holder:"メーカー", ipc:"A61M", kw:"医療 インスリン ポンプ 投与 糖尿病 insulin"},
    {no:"特開2024-009912", field:"医療機器", title:"電子カルテからの重症化予測モデル", desc:"検査値の推移から重症化リスクを早期にアラート。", year:2024, status:"pend", holder:"大学・研究機関", ipc:"G16H", kw:"医療 電子カルテ 予測 重症化 AI EHR"},
    {no:"特許第6566789号", field:"医療機器", title:"超音波画像のAIノイズ低減", desc:"スペックルノイズを抑え、微小構造の視認性を改善。", year:2019, status:"live", holder:"メーカー", ipc:"A61B", kw:"医療 超音波 画像 ノイズ AI ultrasound"},
    {no:"特許第7029988号", field:"医療機器", title:"在宅心電モニタの不整脈検出", desc:"長時間記録から心房細動などを自動検出。", year:2022, status:"live", holder:"スタートアップ・個人", ipc:"A61B", kw:"医療 心電 不整脈 在宅 モニタ ECG"},
    {no:"特開2023-044120", field:"医療機器", title:"低侵襲治療用 操作性マイクロカテーテル", desc:"屈曲部の追従性を高め、到達性と安全性を両立。", year:2023, status:"pend", holder:"メーカー", ipc:"A61M", kw:"医療 カテーテル 低侵襲 治療 catheter 機器"},

    {no:"特許第7101010号", field:"半導体", title:"GaN系パワーデバイスの低オン抵抗構造", desc:"電界集中を緩和する終端構造で高耐圧と低損失を両立。", year:2022, status:"live", holder:"メーカー", ipc:"H01L", kw:"半導体 GaN パワー デバイス 低損失 power"},
    {no:"特許第7056789号", field:"半導体", title:"3次元実装向けの低温銅接合プロセス", desc:"低温で銅同士を接合し、チップレット実装の歩留まり向上。", year:2021, status:"live", holder:"メーカー", ipc:"H01L", kw:"半導体 実装 接合 チップレット 3次元 bonding"},
    {no:"特開2023-031200", field:"半導体", title:"チップレット間の光インターコネクト", desc:"電気配線の限界を超える広帯域・低遅延接続。", year:2023, status:"pend", holder:"スタートアップ・個人", ipc:"H01L", kw:"半導体 光 インターコネクト チップレット photonics"},
    {no:"特許第6604455号", field:"半導体", title:"SiC MOSFETのゲート絶縁膜信頼性向上", desc:"界面欠陥を低減し、長期信頼性を確保。", year:2019, status:"live", holder:"大学・研究機関", ipc:"H01L", kw:"半導体 SiC MOSFET ゲート 信頼性 power"},
    {no:"特許第6955330号", field:"半導体", title:"EUVリソグラフィ向け高感度レジスト材料", desc:"露光感度と解像度を両立する材料設計。", year:2020, status:"live", holder:"メーカー", ipc:"H01L", kw:"半導体 EUV レジスト リソグラフィ 材料 resist"},
    {no:"特開2024-005120", field:"半導体", title:"2次元材料トランジスタの低抵抗接触", desc:"次世代チャネル材料の接触抵抗を大幅に低減。", year:2024, status:"pend", holder:"大学・研究機関", ipc:"H01L", kw:"半導体 2次元材料 トランジスタ 接触 2D"},
    {no:"特許第6510077号", field:"半導体", title:"パワーモジュールの高放熱基板構造", desc:"熱抵抗を下げ、高密度実装での発熱を抑制。", year:2018, status:"live", holder:"メーカー", ipc:"H01L", kw:"半導体 パワーモジュール 放熱 基板 thermal"},
    {no:"特許第7077120号", field:"半導体", title:"AIアクセラレータのデータフロー最適化", desc:"メモリ転送を削減し、電力効率を高める演算配置。", year:2022, status:"live", holder:"スタートアップ・個人", ipc:"G06F", kw:"半導体 AI アクセラレータ データフロー 演算 accelerator"},

    {no:"特許第6844321号", field:"環境・エネルギー", title:"CO2を原料とする樹脂モノマー合成法", desc:"触媒設計で二酸化炭素から有用モノマーを高選択率合成。", year:2021, status:"live", holder:"メーカー", ipc:"C07C", kw:"環境 CO2 二酸化炭素 樹脂 触媒 カーボン carbon"},
    {no:"特許第7120987号", field:"環境・エネルギー", title:"ペロブスカイト太陽電池の耐久化封止構造", desc:"水分侵入を抑える多層封止で屋外耐久性を改善。", year:2022, status:"live", holder:"メーカー", ipc:"H01L", kw:"環境 太陽電池 ペロブスカイト 封止 発電 perovskite"},
    {no:"特開2023-088400", field:"環境・エネルギー", title:"高効率PEM水電解用 低イリジウム触媒", desc:"希少金属使用量を抑えたグリーン水素製造触媒。", year:2023, status:"pend", holder:"大学・研究機関", ipc:"C25B", kw:"環境 水素 水電解 触媒 PEM hydrogen エネルギー"},
    {no:"特許第6677432号", field:"環境・エネルギー", title:"洋上風力の浮体動揺低減制御", desc:"波・風による動揺を抑え、発電効率と寿命を改善。", year:2020, status:"live", holder:"メーカー", ipc:"F03D", kw:"環境 風力 洋上 浮体 制御 wind エネルギー"},
    {no:"特開2024-002201", field:"環境・エネルギー", title:"排水からのリン回収プロセス", desc:"資源として有用なリンを排水から効率回収。", year:2024, status:"pend", holder:"スタートアップ・個人", ipc:"C02F", kw:"環境 排水 リン 回収 資源 phosphorus"},
    {no:"特許第6588120号", field:"環境・エネルギー", title:"直接空気回収(DAC)用 CO2吸着材", desc:"大気中のCO2を低エネルギーで捕集する吸着材。", year:2019, status:"live", holder:"大学・研究機関", ipc:"C01B", kw:"環境 DAC CO2 吸着 回収 carbon capture"},
    {no:"特許第7091200号", field:"環境・エネルギー", title:"VPP向け需給調整アルゴリズム", desc:"分散電源を束ね、需給バランスを自動調整。", year:2021, status:"live", holder:"メーカー", ipc:"H02J", kw:"環境 VPP 需給 調整 電力 grid エネルギー"},
    {no:"特開2023-099001", field:"環境・エネルギー", title:"微生物によるバイオ燃料生産プロセス", desc:"廃資源を原料に微生物で燃料を生産。", year:2022, status:"pend", holder:"スタートアップ・個人", ipc:"C12P", kw:"環境 バイオ燃料 微生物 発酵 biofuel エネルギー"},
    {no:"特許第7155001号", field:"電池・材料", title:"全固体電池用 酸化物系固体電解質の低温焼結法", desc:"低温で緻密化し、量産時のエネルギーコストを抑える焼結プロセス。", year:2023, status:"live", holder:"メーカー", ipc:"H01M", kw:"電池 酸化物 固体電解質 焼結 全固体 材料 oxide"},
    {no:"特開2024-021100", field:"電池・材料", title:"リチウム硫黄電池の正極ホスト材料", desc:"ポリスルフィド溶出を抑える多孔質ホストで容量維持率を改善。", year:2024, status:"pend", holder:"大学・研究機関", ipc:"H01M", kw:"電池 リチウム硫黄 正極 ホスト 材料 sulfur"},
    {no:"特許第6720455号", field:"電池・材料", title:"フッ素フリー電解液添加剤", desc:"被膜形成を促し、高温サイクル特性を高める添加剤組成。", year:2020, status:"live", holder:"メーカー", ipc:"H01M", kw:"電池 電解液 添加剤 被膜 材料 electrolyte"},
    {no:"特許第7233410号", field:"電池・材料", title:"使用済み電池からのレアメタル湿式回収", desc:"コバルト・ニッケルを高純度で選択回収する湿式プロセス。", year:2024, status:"live", holder:"スタートアップ・個人", ipc:"C22B", kw:"電池 リサイクル レアメタル 回収 湿式 recycling 材料"},
    {no:"特開2023-150220", field:"電池・材料", title:"亜鉛二次電池のデンドライト抑制電解質", desc:"水系で安全な亜鉛電池の長寿命化に資する電解質。", year:2023, status:"pend", holder:"大学・研究機関", ipc:"H01M", kw:"電池 亜鉛 水系 デンドライト 電解質 zinc 材料"},
    {no:"特許第6655120号", field:"電池・材料", title:"高容量シリコン負極の自己修復バインダ", desc:"膨張収縮に追従する自己修復ポリマーで寿命を延伸。", year:2019, status:"live", holder:"メーカー", ipc:"H01M", kw:"電池 シリコン 負極 バインダ 自己修復 材料 binder"},
    {no:"特許第7301880号", field:"電池・材料", title:"電池セル内部温度のセンサレス推定", desc:"インピーダンスから内部温度を推定し熱暴走を予防。", year:2024, status:"live", holder:"スタートアップ・個人", ipc:"H01M", kw:"電池 温度 推定 熱暴走 BMS 安全 材料"},
    {no:"特開2022-160330", field:"電池・材料", title:"ナトリウム硬質炭素負極の製造法", desc:"バイオマス由来の硬質炭素で資源制約を緩和。", year:2022, status:"pend", holder:"大学・研究機関", ipc:"H01M", kw:"電池 ナトリウム 硬質炭素 負極 材料 sodium"},
    {no:"特許第6890044号", field:"電池・材料", title:"集電体向け超薄銅箔の表面処理", desc:"密着性と導電性を両立する表面処理で内部抵抗を低減。", year:2021, status:"live", holder:"メーカー", ipc:"H01M", kw:"電池 集電体 銅箔 表面処理 材料 foil"},
    {no:"特許第7166220号", field:"AI・ソフトウェア", title:"検索拡張生成(RAG)の根拠提示手法", desc:"回答に出典スニペットを対応付けて信頼性を高める仕組み。", year:2023, status:"live", holder:"スタートアップ・個人", ipc:"G06F", kw:"AI RAG 検索拡張 LLM 出典 ソフトウェア retrieval"},
    {no:"特開2024-030210", field:"AI・ソフトウェア", title:"オンデバイス話者分離システム", desc:"会議音声を端末上で話者ごとに分離・文字起こし。", year:2024, status:"pend", holder:"メーカー", ipc:"G10L", kw:"AI 音声 話者分離 文字起こし エッジ ソフトウェア diarization"},
    {no:"特許第6733440号", field:"AI・ソフトウェア", title:"勾配秘匿による連合学習プロトコル", desc:"データを共有せず複数拠点でモデルを協調学習。", year:2020, status:"live", holder:"大学・研究機関", ipc:"G06N", kw:"AI 連合学習 プライバシー 秘匿 ソフトウェア federated"},
    {no:"特許第7250010号", field:"AI・ソフトウェア", title:"時系列異常の説明可能スコアリング", desc:"異常箇所の寄与因子を提示するXAI手法。", year:2024, status:"live", holder:"メーカー", ipc:"G06N", kw:"AI 異常検知 説明可能 XAI 時系列 ソフトウェア"},
    {no:"特開2023-130045", field:"AI・ソフトウェア", title:"生成画像の電子透かし埋込・検出", desc:"AI生成物に頑健な透かしを埋め、由来を判定。", year:2023, status:"pend", holder:"スタートアップ・個人", ipc:"G06T", kw:"AI 生成 透かし watermark 検出 ソフトウェア provenance"},
    {no:"特許第6601220号", field:"AI・ソフトウェア", title:"強化学習による配車最適化", desc:"需要予測と連動し待ち時間を最小化する配車制御。", year:2019, status:"live", holder:"メーカー", ipc:"G06Q", kw:"AI 強化学習 配車 最適化 モビリティ ソフトウェア dispatch"},
    {no:"特許第7188990号", field:"AI・ソフトウェア", title:"知識グラフ補完のための関係推論", desc:"欠損リンクを推論し企業・特許の関係を補完。", year:2023, status:"live", holder:"大学・研究機関", ipc:"G06N", kw:"AI 知識グラフ 推論 補完 ソフトウェア knowledge graph"},
    {no:"特開2024-045500", field:"AI・ソフトウェア", title:"LLMエージェントの安全な実行サンドボックス", desc:"ツール実行の権限分離で誤操作・逸脱を防止。", year:2024, status:"pend", holder:"スタートアップ・個人", ipc:"G06F", kw:"AI エージェント サンドボックス 安全 ソフトウェア agent"},
    {no:"特許第6845010号", field:"AI・ソフトウェア", title:"低ビット量子化向け学習補正法", desc:"4bit量子化でも精度劣化を抑える学習時補正。", year:2021, status:"live", holder:"メーカー", ipc:"G06N", kw:"AI 量子化 4bit 推論 圧縮 ソフトウェア quantization"},
    {no:"特許第7144880号", field:"ロボティクス", title:"自律移動ロボットの動的障害物予測回避", desc:"歩行者の動きを予測し滑らかに回避する制御。", year:2023, status:"live", holder:"メーカー", ipc:"G05D", kw:"ロボット 自律移動 障害物 予測 回避 navigation"},
    {no:"特開2024-051200", field:"ロボティクス", title:"模倣学習による器用作業の獲得", desc:"少数デモから精密組立動作を学習。", year:2024, status:"pend", holder:"大学・研究機関", ipc:"B25J", kw:"ロボット 模倣学習 組立 デモ ロボティクス imitation"},
    {no:"特許第6712330号", field:"ロボティクス", title:"配送ロボットの段差乗り越え機構", desc:"小型車輪と補助脚で歩道の段差を安定走破。", year:2020, status:"live", holder:"スタートアップ・個人", ipc:"B62D", kw:"ロボット 配送 段差 機構 ラストワンマイル robot"},
    {no:"特許第7260440号", field:"ロボティクス", title:"多関節アームの衝突回避軌道生成", desc:"動的環境で再計画する高速軌道生成アルゴリズム。", year:2024, status:"live", holder:"メーカー", ipc:"B25J", kw:"ロボット アーム 軌道 衝突回避 計画 motion"},
    {no:"特開2023-140880", field:"ロボティクス", title:"水中点検ロボットの自己位置推定", desc:"濁水下でも安定するソナー融合の自己位置推定。", year:2023, status:"pend", holder:"大学・研究機関", ipc:"G05D", kw:"ロボット 水中 点検 SLAM ソナー underwater"},
    {no:"特許第6620110号", field:"ロボティクス", title:"外骨格スーツの歩行アシスト制御", desc:"装着者の意図を推定し負担を軽減する制御。", year:2019, status:"live", holder:"メーカー", ipc:"A61H", kw:"ロボット 外骨格 アシスト 歩行 福祉 exoskeleton"},
    {no:"特許第7199770号", field:"ロボティクス", title:"群ロボットの分散タスク割当", desc:"通信が限られる環境で自律的に役割分担。", year:2023, status:"live", holder:"スタートアップ・個人", ipc:"G05D", kw:"ロボット 群 分散 タスク割当 swarm ロボティクス"},
    {no:"特開2024-060330", field:"ロボティクス", title:"柔軟マニピュレータの形状推定", desc:"内蔵センサからしなやかなアームの形状を復元。", year:2024, status:"pend", holder:"大学・研究機関", ipc:"B25J", kw:"ロボット 柔軟 マニピュレータ 形状推定 soft robot"},
    {no:"特許第6905510号", field:"医療機器", title:"連続血糖モニタの校正補正アルゴリズム", desc:"指先採血を減らす自己校正で精度を維持。", year:2021, status:"live", holder:"メーカー", ipc:"A61B", kw:"医療 血糖 CGM 校正 糖尿病 glucose 機器"},
    {no:"特開2024-070110", field:"医療機器", title:"AIによる胸部X線の異常スクリーニング", desc:"複数所見を同時検出し読影を支援。", year:2024, status:"pend", holder:"大学・研究機関", ipc:"G16H", kw:"医療 X線 AI スクリーニング 読影 chest 機器"},
    {no:"特許第6733900号", field:"医療機器", title:"カプセル内視鏡の体内位置推定", desc:"磁場を利用しカプセルの位置を高精度推定。", year:2020, status:"live", holder:"メーカー", ipc:"A61B", kw:"医療 カプセル 内視鏡 位置推定 capsule 機器"},
    {no:"特許第7277010号", field:"医療機器", title:"在宅人工呼吸器のリーク自動補正", desc:"マスク漏れを検知し換気量を自動補正。", year:2024, status:"live", holder:"メーカー", ipc:"A61M", kw:"医療 人工呼吸器 リーク 換気 在宅 ventilator 機器"},
    {no:"特開2023-160770", field:"医療機器", title:"超音波による非侵襲血圧連続計測", desc:"カフレスで連続的に血圧を推定するプローブ。", year:2023, status:"pend", holder:"大学・研究機関", ipc:"A61B", kw:"医療 血圧 非侵襲 超音波 カフレス blood pressure 機器"},
    {no:"特許第6644220号", field:"医療機器", title:"手術支援ロボットの力覚フィードバック", desc:"組織への接触力を術者に提示し安全性を向上。", year:2019, status:"live", holder:"メーカー", ipc:"A61B", kw:"医療 手術支援 ロボット 力覚 触覚 surgical 機器"},
    {no:"特許第7211220号", field:"医療機器", title:"ウェアラブル心音解析による弁膜症検出", desc:"装着型マイクで心雑音を解析しリスクを推定。", year:2023, status:"live", holder:"スタートアップ・個人", ipc:"A61B", kw:"医療 心音 弁膜症 ウェアラブル 解析 heart 機器"},
    {no:"特開2024-080220", field:"医療機器", title:"点滴投与の気泡検知・自動停止", desc:"微小気泡を検知し安全に投与を停止する機構。", year:2024, status:"pend", holder:"メーカー", ipc:"A61M", kw:"医療 点滴 気泡 検知 安全 infusion 機器"},
    {no:"特許第7120440号", field:"半導体", title:"裏面照射型イメージセンサの低ノイズ画素", desc:"暗電流を抑える画素構造で高感度撮像を実現。", year:2022, status:"live", holder:"メーカー", ipc:"H01L", kw:"半導体 イメージセンサ 画素 低ノイズ CMOS sensor"},
    {no:"特開2024-090110", field:"半導体", title:"GaN HEMTのノーマリオフ化構造", desc:"安全動作に必要なノーマリオフを実現するゲート構造。", year:2024, status:"pend", holder:"大学・研究機関", ipc:"H01L", kw:"半導体 GaN HEMT ノーマリオフ パワー power"},
    {no:"特許第6700330号", field:"半導体", title:"先端ロジック向けEUVマスク欠陥検査", desc:"微小欠陥を高速検出するマスク検査手法。", year:2020, status:"live", holder:"メーカー", ipc:"H01L", kw:"半導体 EUV マスク 欠陥 検査 lithography"},
    {no:"特許第7288820号", field:"半導体", title:"ハイブリッドボンディングの位置合わせ精度向上", desc:"ナノ精度の位置合わせで3D実装の歩留まりを改善。", year:2024, status:"live", holder:"メーカー", ipc:"H01L", kw:"半導体 ハイブリッドボンディング 3D 実装 bonding"},
    {no:"特開2023-170550", field:"半導体", title:"強誘電体メモリ(FeRAM)の保持特性改善", desc:"分極疲労を抑える材料積層で保持時間を延長。", year:2023, status:"pend", holder:"大学・研究機関", ipc:"H01L", kw:"半導体 強誘電体 FeRAM メモリ 保持 ferroelectric"},
    {no:"特許第6622110号", field:"半導体", title:"パワーIC向け高効率DC-DC統合回路", desc:"高速スイッチングで小型・高効率な電源IC。", year:2019, status:"live", holder:"メーカー", ipc:"H02M", kw:"半導体 DC-DC 電源 IC 高効率 power"},
    {no:"特許第7233990号", field:"半導体", title:"アナログインメモリ演算による省電力AIチップ", desc:"メモリ上で積和演算しデータ移動を削減。", year:2024, status:"live", holder:"スタートアップ・個人", ipc:"G11C", kw:"半導体 インメモリ AI 省電力 演算 in-memory"},
    {no:"特開2024-095010", field:"半導体", title:"SiCウェハの欠陥低減エピ成長", desc:"基底面転位を抑えるエピ成長で歩留まりを改善。", year:2024, status:"pend", holder:"メーカー", ipc:"H01L", kw:"半導体 SiC エピ 欠陥 結晶 epitaxy"},
    {no:"特許第6588330号", field:"半導体", title:"ガラスインターポーザの貫通配線形成", desc:"高速・低損失な貫通配線をガラス基板に形成。", year:2019, status:"live", holder:"メーカー", ipc:"H01L", kw:"半導体 ガラス インターポーザ TGV 配線 interposer"},
    {no:"特許第7177440号", field:"環境・エネルギー", title:"アニオン交換膜形水電解の高耐久電極", desc:"白金フリーで耐久性の高い水素製造用電極。", year:2023, status:"live", holder:"大学・研究機関", ipc:"C25B", kw:"環境 水素 水電解 AEM 電極 hydrogen エネルギー"},
    {no:"特開2024-100330", field:"環境・エネルギー", title:"使用済みプラスチックのケミカルリサイクル触媒", desc:"混合プラを温和な条件で単量体に分解。", year:2024, status:"pend", holder:"メーカー", ipc:"C08J", kw:"環境 プラスチック ケミカルリサイクル 触媒 recycling エネルギー"},
    {no:"特許第6712990号", field:"環境・エネルギー", title:"系統用ナトリウム硫黄蓄電の長寿命運用法", desc:"温度管理と運用制御で寿命を延ばす蓄電システム。", year:2020, status:"live", holder:"メーカー", ipc:"H01M", kw:"環境 蓄電 NAS 系統 長寿命 storage エネルギー"},
    {no:"特許第7299010号", field:"環境・エネルギー", title:"EV向け双方向充電(V2G)制御", desc:"系統需給に応じて充放電を最適化する制御。", year:2024, status:"live", holder:"スタートアップ・個人", ipc:"H02J", kw:"環境 EV V2G 双方向 充電 grid エネルギー"},
    {no:"特開2023-180220", field:"環境・エネルギー", title:"低濃度メタンの常温酸化触媒", desc:"換気廃ガス中の希薄メタンを常温付近で処理。", year:2023, status:"pend", holder:"大学・研究機関", ipc:"B01J", kw:"環境 メタン 触媒 温暖化 methane エネルギー"},
    {no:"特許第6644990号", field:"環境・エネルギー", title:"浮体式洋上太陽光の係留・耐波構造", desc:"波浪荷重を分散し沖合で発電する浮体構造。", year:2019, status:"live", holder:"メーカー", ipc:"H02S", kw:"環境 洋上 太陽光 浮体 発電 floating エネルギー"},
    {no:"特許第7211990号", field:"環境・エネルギー", title:"地中熱ヒートポンプの高効率熱交換器", desc:"掘削長を短縮しつつ熱交換効率を高める設計。", year:2023, status:"live", holder:"メーカー", ipc:"F24T", kw:"環境 地中熱 ヒートポンプ 熱交換 geothermal エネルギー"},
    {no:"特開2024-110440", field:"環境・エネルギー", title:"バイオ炭による土壌炭素貯留の評価法", desc:"炭素貯留量を定量化しクレジット化を支援。", year:2024, status:"pend", holder:"スタートアップ・個人", ipc:"C05F", kw:"環境 バイオ炭 炭素貯留 クレジット biochar エネルギー"},
    {no:"特許第6733110号", field:"環境・エネルギー", title:"排熱回収用熱電変換モジュール", desc:"工場排熱から発電する高出力熱電モジュール。", year:2020, status:"live", holder:"メーカー", ipc:"H10N", kw:"環境 排熱 熱電 発電 thermoelectric エネルギー"}
  ];

